FROM debian:bookworm-slim

RUN useradd --no-create-home -u 1000 user

RUN apt update && \
    apt install -y socat policycoreutils && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /home/user

COPY chal flag.txt ./

RUN chmod +x chal && \
    chcon -t bin_t chal

USER user

CMD socat -T60 TCP-LISTEN:1337,reuseaddr,fork EXEC:"./chal"
